### ISSUE TITLE
Data models/tables

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#10]
### Todos:
- [x] add `published_at` field to `comics` & `chapters`
- [x] add `is_visible` field to `comics` & `chapters`
- [x] add `bio` field to `users`
- [x] add `user_links` table (limit user links to 3)
- [x] add posters to comics by adding `poster_path` & `poster_content_type` fields
- [x] add `title` field to `chapters`
