### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#11]
Authentication will be session-based

it will store the user session on login, and remove it on logout.
it will refresh authenticated users sessions on every API call.

### Todos:
**login:**
- [x] create session in DB
- [x] prevent already logged in users
- [x] add session id to cookie

**logout:**
- [x] delete session from DB
- [x] only allow logged in users
- [x] remove session id cookie

**others:**
- [x] #19
- [x] refresh active sessions with middleware
- [x] #37
- [x] remove cookie on InvalidSession errors
