### ISSUE TITLE
Comic/Chapters comments

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#14]
add comments to both chapters and comics

chapter and comic comments should have different tables to differentiate between them

comments will have children comments and parent comments so this can be done by adding a `comment_parents_children` table that connects parents and children 

models:

```rust
// POST /api/v1/comics/chapters/:chapter_id/comments
struct CreateChapterComment {
    content: String,
}
```

```rust
// POST /api/v1/comics/:comic_id/comments
struct CreateComicComment {
    content: String,
}
```
------
**UPDATE:**
since having to render comments recursively with it's child comments, it seems a bit unnecessary and over complicated for what is important, to make it simple, it could be simplified to only have one level of comments replies like so:

1- table for comments on comics/chapters
2- table for replies on comments

with relations:
one comic to many comments
one comment to many replies

and that's it :)

OR only render 1 level of comment replies then require the user to enter the thread to get to the children of the reply

but it still feels a bit unnecessary for an indie comic platform to have so much depth to the comments and replies

but we will see what the future holds :)

------
**UPDATE2:**
I figured out a way to send the necessary data to the client, by inlining diesel's `belonging_to()` function:

```rust
    let comment_mappings_by_parents = comment_mappings.clone().grouped_by(&comments); // 1 parent -> children

    let id_indices: HashMap<_, _> = comments
        .iter()
        .enumerate()
        .map(|(i, u)| (u.id, i))
        .collect();

    let mut comment_mappings_by_children = comments.iter().map(|_| Vec::new()).collect::<Vec<_>>();

    for child in comment_mappings {
        comment_mappings_by_children[id_indices[&child.child_comment_id]].push(child);
    }
```

and adding the parent id to the comment struct:

```rust
pub struct ComicCommentResponse {
    pub id: Uuid,
    pub content: String,
    pub user: UserResponseBrief,
    pub parent_comment: Option<Uuid>, // this part
    pub child_comments: Option<Vec<Uuid>>,
}
```
now in the frontend, I can first get the top level comments aka the ones with no parents, then recursively add the children to them. [frontend implementation](https://github.com/BKSalman/musawarah/issues/22)

------

### Todos:
- [x] create chapter_comments migration
- [x] create chapter_comments_parents_children migration
- [x] create comic_comments migration
- [x] create comic_comments_parents_children migration
- [x] handler for creating comments that recieves `CreateComment` as payload and gets current user with `AuthExtractor`
- [x] save comment to DB
- [x] link comments to parent comments
- [x] handler for deleting comments
- [x] handler to get chapter comments
- [x] handler to get comic comments
