### ISSUE TITLE
User verification

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#18]
verify user accounts by sending a verification email or something

1- create `email_verifications` table, could use a table like this:
```sql
CREATE TABLE IF NOT EXISTS email_verifications (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    user_id UUID NOT NULL,
);
```
2- send email to user
3- handler takes in the token and verifies the user if it didn't expire

\+ do I need to check if the email actually exists? if so I could use [this](https://github.com/reacherhq/check-if-email-exists)

### Todos:
- [x] add roles check to routes #19 
- [x] add `VerifiedUser` role
- [x] send emails
- [x] `email_verifications` table
- [x] handler for verifying email
- [x] verification mechanism

**Comment by mohad12211** [comment]
1. why is it important to check that the email exists before sending? 
2. should we use this to send emails: https://github.com/lettre/lettre ?
3. for how long should the verification be valid? 
4. what is meant by "verification mechanism"?

**Comment by BKSalman** [comment]
> * why is it important to check that the email exists before sending?

not really, was just thinking

> * should we use this to send emails: https://github.com/lettre/lettre ?

yes it works
 
> * for how long should the verification be valid?

probably like an hour

> * what is meant by "verification mechanism"?

either a URL that the user clicks, or OTP, etc. etc.

**Comment by mohad12211** [comment]
so I suppose that because we have a `User` role and a `VerifiedUser` role, a user can login with his unverified account, so when should I show "You need to verify your email address" message?

**Comment by mohad12211** [comment]
or should we wait for that until we have a settings page in the user profile, where we show the message?

**Comment by mohad12211** [comment]
> either a URL that the user clicks, or OTP, etc. etc.

I dont see a big difference, I would do a URL, is it ok?

**Comment by BKSalman** [comment]
> so I suppose that because we have a User role and a VerifiedUser role, a user can login with his unverified account, so when should I show "You need to verify your email address" message?

probably when they go to their profile

**Comment by BKSalman** [comment]
> I dont see a big difference, I would do a URL, is it ok?

no problem
