### ISSUE TITLE
Comic page

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#22]
### Relevant resources:

- [resursive svelete components](https://svelte.dev/repl/347b37e18b5d4a65bbacfd097536db02?version=3.24.0)

to render the nested comments provided by the backend as IDs we need to recursively fill the children comments:

```ts
const fill_children = (comment: ComicCommentResponse, comments: ComicCommentResponse[], limit: number) => {
    if (limit <= 0) {
        comment.child_comments = [];
        return;
    }

    comment.child_comments = comment.child_comments?.map((child_id) => {
        const child_comment = get_comment_by_id(child_id, comments);

        if (child_comment) {
            console.log(child_comment);
            fill_children(child_comment, comments, limit - 1);

            return child_comment;
        }
    });
}

const get_comment_by_id = (id: string, comments: ComicCommentResponse[]): ComicCommentResponse | undefined => {
    return comments.find((comment) => {
        return comment.id == id;
    });
}
```

### Todos:
- [x] render nested comments
    - [x] fill comment children in object
    - [x] list in UI (https://svelte.dev/repl/347b37e18b5d4a65bbacfd097536db02?version=3.24.0)
    - [x] add comment box and a message for non-logged in users
- [x] add a way to create chapters in the comic page ( could be a + button or something )
- [x] list chapters (maybe in a grid)
