### ISSUE TITLE
Global overlay

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#24]
this issue is for the frontend overlay that lives in the `+layout.svelte` file

### Todo:

- [x] Make NavBar Sticky
- [x] Make SideBar Sticky
- [x] make footer show properly 
- [ ] see how can we add popup when clicking user pfp
